networks:
    hospital_reservations-api-dev:
        driver: bridge
    traefik-proxy-hospital_reservations-local:
        external: true

volumes:
    hospital_reservations-postgres-data:
        name: hospital_reservations-postgres-data
    hospital_reservations-redis-data:
        name: hospital_reservations-redis-data

services:
    app:
        build:
            context: ./environment/dev/app
            dockerfile: Dockerfile
            args:
                - INSTALL_XDEBUG=${DOCKER_INSTALL_XDEBUG:-true}
                - USER_ID=${DOCKER_HOST_USER_ID:-1000}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hospital_reservations-api-http-router.rule=Host(`${APP_URL:-hospital_reservations-api.localhost}`)"
            - "traefik.http.routers.hospital_reservations-api-http-router.entrypoints=web"
        container_name: hospital_reservations-api-app-dev
        working_dir: /application
        volumes:
            - ./environment/dev/app/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./environment/dev/app/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
            - ./environment/dev/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
            - ./environment/dev/app/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
            - .:/application
        ports:
            - ${DOCKER_APP_HOST_PORT:-63851}:80
        networks:
            - hospital_reservations-api-dev
            - traefik-proxy-hospital_reservations-local
        restart: unless-stopped
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:16.3-alpine3.18
        container_name: hospital_reservations-db-dev
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - PGDATA=/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --dbname ${DB_DATABASE} --username ${DB_USERNAME}"]
            interval: 3s
            timeout: 3s
            retries: 5
        ports:
            - ${DOCKER_DATABASE_HOST_PORT:-63853}:5432
        volumes:
            - hospital_reservations-postgres-data:/var/lib/postgresql/data
        networks:
            - hospital_reservations-api-dev
        restart: unless-stopped

    mailpit:
      image: axllent/mailpit:v1.18.0
      container_name: hospital_reservations-mailpit-dev
      labels:
        - "traefik.enable=true"
        # HTTP
        - "traefik.http.routers.hospital_reservations-mailpit-http-router.rule=Host(`hospital_reservations-mailpit.localhost`)"
        - "traefik.http.routers.hospital_reservations-mailpit-http-router.entrypoints=web"
        # LOADBALANCER MAILPIT PORT
        - "traefik.http.services.hospital_reservations-mailpit.loadbalancer.server.port=8025"
      networks:
        - hospital_reservations-api-dev
        - traefik-proxy-hospital_reservations-local
      ports:
        - ${DOCKER_MAILPIT_DASHBOARD_HOST_PORT:-63854}:8025
      restart: unless-stopped

    redis:
        image: redis:7.2.4-alpine3.19
        container_name: hospital_reservations-redis-dev
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-63852}:6379
        volumes:
            - hospital_reservations-redis-data:/data
        networks:
            - hospital_reservations-api-dev
        restart: unless-stopped
